# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u540d\u5b57')),
                ('origin', models.CharField(max_length=128, verbose_name='\u4ea7\u5730')),
            ],
        ),
    ]
