# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u59d3\u540d')),
                ('gender', models.BooleanField(verbose_name='\u59d3\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorToBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u4e66\u540d')),
                ('summary', models.CharField(max_length=128, verbose_name='\u7b80\u4ecb')),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u51fa\u7248\u793e\u540d\u79f0')),
                ('addr', models.CharField(max_length=64, verbose_name='\u5730\u5740')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='press',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Press'),
        ),
        migrations.AddField(
            model_name='authortobook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Book'),
        ),
    ]
