# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authortobook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authortobook',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='app01.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.BooleanField(verbose_name='\u6027\u522b'),
        ),
        migrations.DeleteModel(
            name='AuthorToBook',
        ),
    ]
